### ISSUE TITLE
Certificate chain with intermediate authority

### ISSUE THREAD

**Issue by Enucatl** [southalc/vault#17]
Hi, I have a setup where my vault has a root CA (which we call _a_), which was used to sign an intermediate CA (_b_). _b_ is then used to sign server (_s_) certificates.

I think this module produces certificates in [vault/lib/puppet/provider/vault_cert/vault_cert.rb](https://github.com/southalc/vault/blob/master/lib/puppet/provider/vault_cert/vault_cert.rb#L330) in a way that is harder to use in my (relatively common) use case.

We get three files, containing:

```
ca_chain: [b, a]
cert: [s, b]
privkey: [s]
```

As a result, whenever I distribute the `cert` file to applications that only have the [a] ca file, they are not able to verify it.

I think we should follow the way that [letsencrypt's certbot](https://eff-certbot.readthedocs.io/en/stable/api/certbot.interfaces.html?highlight=fullchain#certbot.interfaces.RenewableCert) is using:
```
fullchain: [s, b, a]
cert: [s]
privkey: [s]
```
they also provide a `chain` with only [b, a], but I've never seen it used anywhere, plus it would be more work to add another output, while here we can just reuse either `cert` (for backwards compatibility within this package) or `ca_chain` (closer to certbot's fullchain name):

```ruby
# line 330
      @property_flush[:ca_chain] = cert_info['data']['ca_chain'].join("\n")
      @property_flush[:cert] = [cert_info['data']['certificate'], cert_info['data']['ca_chain'].join("\n")].join("\n")
      @property_flush[:key] = cert_info['data']['private_key']
## or
      @property_flush[:ca_chain] = [cert_info['data']['certificate'], cert_info['data']['ca_chain'].join("\n")].join("\n")
      @property_flush[:cert] = cert_info['data']['certificate']
      @property_flush[:key] = cert_info['data']['private_key']
```

I went with option 1 in my fork

**Comment by southalc** [comment]
I appreciate this suggestion and agree that it would be better to bundle the host certificate with the issuing CA certificate(s) in the chain file.  I have another couple things I'm reviewing in this type/provider and will have an update in the near future.

**Comment by southalc** [comment]
I've included this change in the new "ca_chain" branch.  Once I've had a chance to test a little further I'll merge this and post the new release to puppet forge.

**Comment by southalc** [comment]
This feature has been merged to the master branch, tagged as version 0.6.0, and posted to the puppet forge.

**Comment by optiz0r** [comment]
Thanks for fixing this, I appear not to have subscribed to issues in this repo. The original parameters were modelled after the way apache configs work, which expected the leaf cert in one file, and the chain in a separate file. Having the first intermediate cert into the leaf cert file in retrospect was a mistake, I can't remember why I did that. I think the new way of doing things is much cleaner :+1:
